##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  morpho配置  ###################
morpho:
  system-sysname: morpho-springboot
  system-copyright: www.max256.com
  login-allow-attempt-num: 3
  login-enable-captch: false
  login-enable-retry-limit: false
  login-lock-time: 60
  sys-resource-generate-flag: false 
  muti-datasource-open: false
  enable-javamelody: true
  enable-http-request-log: true
  javamelody-aop-reg-exp: 
  xss-filter-paths: 
  

###################  项目启动端口  ###################


server:
  port: 8082
  servlet-path: /

  
###################  健康检查  ###################
management:  
  port: 8082
  health:  
    mail:  
      enabled: false  
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false  
  app:  
    name: "@project.name@" #从pom.xml中获取  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"  

###################  MyBatis 配置  ###################
mybatis:
    type-aliases-package: com.max256.morpho.common.entity,com.max256.morpho.sys.entity
    mapper-locations: classpath:dao/*.xml


###################  MyBatis 分页插件配置  ###################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    autoRuntimeDialect: true

###################  MyBatis Mapper配置  ###################
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL
    
    
###################  shiro配置  ###################    
shiro:
  credentials-matcher-hash-algorithm-name: md5
  credentials-matcher-hash-iterations: 2
  credentials-matcher-stored-credentials-hex-encoded: true
  form-authc-password-param: usrn
  form-authc-username-param: usrp
  login-url: /login
  success-url: /index
  unauthorized-url: /login
  enable-remember-me: false
  enable-redis-session: false
  delete-invalid-sessions: true
  global-session-timeout: 1800000
  session-validation-interval: 60000
  session-validation-scheduler-enabled: true
  remember-me-param: rememberMe
  

###################  spring配置  ###################
spring:
  boot:  
    admin:  
      url: http://127.0.0.1:9001/
     
     
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 3000
    pool:
      max-idle: 10
      min-idle: 2
      max-active: 10
      max-wait: 1000
    
    
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: true
    servlet:
      load-on-startup: 1
      
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
             
       


  http:
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
    auto: true
---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://193.0.10.211:3306/morpho?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat
      enable-web-admin: true
      web-admin-username: admin
      web-admin-password: 123456
      
     

#多数据源
morpho:
  muti-datasource:
    default-dataSource-name: dataSourceMorpho #默认的数据源名称
    url: jdbc:mysql://127.0.0.1:3306/morpho1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

logging:
  config: classpath:log4j2.xml
  level:
    root: info
  path: logs-test/
  file: morpho.log

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/morpho?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat
      enable-web-admin: true
      web-admin-username: admin
      web-admin-password: 123456
     

logging:
  config: classpath:log4j2.xml
  level:
    root: info
  path: logs/
  file: morpho.log

